---
- name: BLACKBOX_EXPORTER | Ensure blackbox_exporter group
  group:
    name: "{{ blackbox_exporter_group }}"
    system: true
    state: present

- name: BLACKBOX_EXPORTER | Ensure blackbox_exporter user
  user:
    name: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    system: true
    shell: /usr/sbin/nologin
    createhome: false

- name: BLACKBOX_EXPORTER | Ensure skeleton paths
  file:
    dest: "{{ item }}"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    state: directory
  with_items:
    - "{{ blackbox_exporter_skeleton_paths }}"

- name: BLACKBOX_EXPORTER | Ensure skeleton log paths
  file:
    dest: "{{ item }}"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    state: directory
  with_items:
    - "{{ blackbox_exporter_log_path }}"
  when: blackbox_exporter_log_path is defined

- name: BLACKBOX_EXPORTER | Check blackbox_exporter version
  command: blackbox_exporter -version
  register: blackbox_exporter_check
  changed_when: false
  ignore_errors: true

- name: BLACKBOX_EXPORTER | Download package
  get_url:
    url: "{{ blackbox_exporter_url }}"
    dest: "{{ blackbox_exporter_package_path }}"
  when: blackbox_exporter_force_reinstall or blackbox_exporter_check is failed or blackbox_exporter_version not in blackbox_exporter_check.stderr

- name: BLACKBOX_EXPORTER | Extract downloaded package
  unarchive:
    src: "{{ blackbox_exporter_package_path }}"
    dest: "{{ blackbox_exporter_download_path }}"
    remote_src: true
  when: blackbox_exporter_force_reinstall or blackbox_exporter_check is failed or blackbox_exporter_version  not in blackbox_exporter_check.stderr

- name: blackbox_exporter | Copy binary
  copy:
    src: "{{ blackbox_exporter_src_bin }}"
    dest: "{{ blackbox_exporter_bin_path }}/{{ blackbox_exporter_exec_name }}"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    remote_src: true
    mode: 0755
  when: blackbox_exporter_force_reinstall or blackbox_exporter_check is failed or blackbox_exporter_version not in blackbox_exporter_check.stderr

- name: blackbox_exporter | Link binary
  file:
    src: "{{ blackbox_exporter_bin_path }}/{{ blackbox_exporter_exec_name }}"
    dest: "/usr/bin/{{ blackbox_exporter_exec_name }}"
    state: link
  when: blackbox_exporter_force_reinstall or blackbox_exporter_check is failed or blackbox_exporter_version not in blackbox_exporter_check.stderr
