---

- name: BLACKBOX_EXPORTER | Configuring service
  systemd:
    name: blackbox_exporter
    state: "{{ blackbox_exporter_service_state }}"
    enabled: "{{ blackbox_exporter_service_enabled }}"
    daemon_reload: yes
